axis_linear: 1
scale_linear: 0.4
scale_linear_turbo: 1 # 3.6 MAX - 1 recommended
scale_angular_turbo: 1 # 14.389 MAX - 1 recommended

axis_angular: 0
scale_angular: 1 #7.19 MAX

enable_button: 6  # L2 shoulder button
enable_turbo_button: 4  # L1 shoulder button
