axis_linear: 1
scale_linear: 1.8
scale_linear_turbo: 3.6 # 3.6 MAX
scale_angular_turbo: 6 # 14.389 MAX

axis_angular: 0
scale_angular: 3 #7.19 MAX

enable_button: 6  # L2 shoulder button
enable_turbo_button: 4  # L1 shoulder button
